experiment:
  mode: manual
  seed: 0

model:
  path: /home/naren/naren_research/Beyond-Discrete-Personas/naren_research/personality-trait-enhancing/ollama-personality-finetuning/outputs/plasticity_low-qwen3-1.7b-personality-merged
  # name: plasticity_low-qwen3-1.7b-personality-merged # Optional, using path for loading
  cache_dir: llm_weights
  save_path: llm_weights
  save_activations: false

server:
  host: 0.0.0.0
  port: 8005

knowledge_drift:
  enabled: false

prompt:
  type: custom
  subject:
  length:
  custom_text:

pruning:
  enabled: true
  layer_topk:
  masking_step:
  release_step:
  ema_decay:
  ranking_method: "magnitude"
  prune_strategy: "topk"
  total_prune_percent: 0.0
  generation_tokens: 0
  verbose: true

evaluation:
  perplexity:
    enabled: false
    datasets: ["custom", "mmlu"]
    subjects:
    max_samples:
  mmlu:
    enabled: false
    datasets: ["college_computer_science", "machine_learning", "electrical_engineering", "business_ethics", "world_religions", "prehistory", "moral_disputes"]
    shots: 0
    max_samples:
  general_nlp:
    enabled: false
    datasets:
    max_samples:
  summarization:
    enabled: false
    datasets: ['multi_news', 'xsum', 'cnn_dailymail']
    max_samples:
    max_output: 256

results:
  base_dir:
